model:
  name: "Qwen/Qwen2.5-3B-Instruct"
  lora_rank: 16
  max_seq_length: 512
  load_in_4bit: true
  fast_inference: true
  gpu_memory_utilization: 0.5
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
  lora_alpha: 64
  use_gradient_checkpointing: "unsloth"
  random_state: 0

training:
  learning_rate: 0.00002
  warmup_ratio: 0.03
  per_device_train_batch_size: 32
  gradient_accumulation_steps: 8
  num_generations: 16
  max_completion_length: 512
  adam_beta1: 0.9
  adam_beta2: 0.99
  weight_decay: 0.1
  max_grad_norm: 0.1
  max_steps: 400
  save_steps: 1
  output_dir: "outputs"
  logging_steps: 1
  lr_scheduler_type: "cosine"
  optim: "adamw_8bit"

inference:
  checkpoint_name: "checkpoint-400"
  gpu_memory_utilization: 0.6
  batch_size: 16

path_data: "data"
log_dir: completions_grpo/test_run2